sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  - postgresql

env:
  global:
    - DB=postgres
    - DATABASE_URL=postgis://postgres@localhost:5432/travis_ci_test
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
   - DJANGO="Django<1.12"
   - DJANGO="Django<2.1"

cache:
  directories:
   - $HOME/.cache/pip

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - libgdal-dev

install:
 - pip install "$DJANGO" codecov pipenv
 - pipenv install --dev
 - pip install .

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database travis_ci_test;' -U postgres

script: make lint test && codecov
