sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
   - DJANGO="Django<1.12"
   - DJANGO="Django<2.1"

cache:
  directories:
   - $HOME/.cache/pip

install:
 - pip install "$DJANGO" codecov pipenv
 - pipenv install --dev
 - pip install .

script: make test && codecov
